# pulling base node image of latest version with alpine linux 
FROM node:alpine AS base 

# -- Stage 1: installing depedencies
FROM base AS deps
# translator for optimizers used in nextjs and alpine linux
RUN apk add --no-cache libc6-compat
# set working dir on the container
WORKDIR /app
# copy dependecies from project root to working dir of container
COPY package.json package-lock.json* ./
# npm clean install ( removes node_modules )
RUN npm ci

# -- Stage 2: building the application
FROM base AS builder
# set working dir on the container
WORKDIR /app
# copy dependencies from deps container to builder container
COPY --from=deps /app/node_modules ./node_modules
# copy all files from project root to container working dir
COPY ./ ./
# stops sending telemetry data to vercel
ENV NEXT_TELEMETRY_DISABLED=1
# build the applicaion
RUN npm run build

# -- Stage 3: Run the application
FROM base AS runner
# set working directory
WORKDIR /app
# enviroment var to set production enviroment
ENV NODE_ENV=production
# stops sending telemetry data to vercel
ENV NEXT_TELEMETRY_DISABLED=1

# Create a non-root user for security
RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

# copy assets folder
COPY --from=builder ./app/public ./public
# copy minified dependencies and server.js
COPY --from=builder --chown=nodejs:nextjs ./app/.next/standalone ./
# copy js bundles and global css
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

# switch to non-root user before running the application
USER nextjs

EXPOSE 3000
ENV PORT=3000
ENV HOSTNAME="0.0.0.0"

# server.js is automatically generated by the "standalone" output
CMD ["node", "server.js"]





